[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".tmux/plugins/tpm"]
  type = "archive"
  url = "https://github.com/tmux-plugins/tpm/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
