#!/bin/bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    user " - Do you want to sign your commits? [y/N]"
    read -e verified

    if [ "$verified" == "y" ]
    then
      # Check if a GPG key already exists
      existing_keys=$(gpg --list-secret-keys --keyid-format LONG)
    
      if [[ -n "$existing_keys" ]]; then
        # Extract the GPG key ID from the existing keys
        gpg_key_id=$(echo "$existing_keys" | grep -E "^sec" | awk '{print $2}' | cut -d '/' -f 2)
        # info "You already have an existing GPG key. Your GPG key ID is: $gpg_key_id"
      else
        # Generate a new GPG key
        gpg --full-generate-key

        # Extract the GPG key ID from the newly generated key
        gpg_key_id=$(gpg --list-secret-keys --keyid-format LONG | grep -E "^sec" | awk '{print $2}' | cut -d '/' -f 2)
        info "GPG key generated successfully. Your GPG key ID is: $gpg_key_id"
        
      fi
        sed -e "s/GPGSIGNINGKEY/$gpg_key_id/g" -e "s/VERIFY/true/g" git/gitconfig.local.symlink > git/gitconfig.local.symlink.tmp \
        && mv git/gitconfig.local.symlink.tmp git/gitconfig.local.symlink

        # Print the GPG public key
        gpg --armor --export $gpg_key_id
    else
      sed -e "s/VERIFY/false/g" git/gitconfig.local.symlink > git/gitconfig.local.symlink.tmp \
        && mv git/gitconfig.local.symlink.tmp git/gitconfig.local.symlink
    fi

    success 'gitconfig'
  fi
}


link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'Installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

user ' - Personal Setup? [Y/n]'
read personal_setup

setup_gitconfig
install_dotfiles

dot_file_cmd="source bin/dot --personal"

if [[ $personal_setup != "n" ]]; then
  dot_file_cmd="source bin/dot --personal"
else
  dot_file_cmd="source bin/dot --work"
fi

info "Installing dependencies"
if eval "$dot_file_cmd" | while read -r data; do info "$data"; done
then
  success "Dependencies installed"
else
  fail "Error installing dependencies"
fi

echo ''
echo '  All installed! Please open a new Terminal window.'

