#!/bin/bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# find the migrations and run them iteratively
find ./migrations -name '*.sh' | while read migration ; do /bin/bash -c "${migration}" ; done

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do /bin/bash -c "${installer}" ; done
